//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmas_22_Activity_Check_In.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Build a Bear")]
        public string aciName {
            get {
                return ((string)(this["aciName"]));
            }
            set {
                this["aciName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jadzia1984!")]
        public string aciFTPPassword {
            get {
                return ((string)(this["aciFTPPassword"]));
            }
            set {
                this["aciFTPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("access802899325.webspace-data.io")]
        public string aciFTPHost {
            get {
                return ((string)(this["aciFTPHost"]));
            }
            set {
                this["aciFTPHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1111")]
        public string aciPin {
            get {
                return ((string)(this["aciPin"]));
            }
            set {
                this["aciPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u98941559")]
        public string aciFTPUsername {
            get {
                return ((string)(this["aciFTPUsername"]));
            }
            set {
                this["aciFTPUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int aciFTPPort {
            get {
                return ((int)(this["aciFTPPort"]));
            }
            set {
                this["aciFTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/uzmQIAHBSH6kusMp9tNpbSvEn5IGJKaB5ESX3WUWmPeMVNRnBFxudnt4ubtaAfbJ")]
        public string aciRFChild {
            get {
                return ((string)(this["aciRFChild"]));
            }
            set {
                this["aciRFChild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/hQDo6TUAuImqWENYQjdjMHhdKeiFYqsvMKhMPNBgM7oXUCNkXB4rtBH7i3tYubYh")]
        public string aciRFAdult {
            get {
                return ((string)(this["aciRFAdult"]));
            }
            set {
                this["aciRFAdult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/3hbQnlLEQA870bKszQg8dIWQ5cLzZm2wOCJj5zym0eFKZwgBn2T0ZS9i03fit53q")]
        public string aciRFFamily {
            get {
                return ((string)(this["aciRFFamily"]));
            }
            set {
                this["aciRFFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ashcr\\Downloads\\New folder")]
        public string aciLocalSave {
            get {
                return ((string)(this["aciLocalSave"]));
            }
            set {
                this["aciLocalSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ashcr\\Downloads\\New folder\\Backup")]
        public string aciLocalBackup {
            get {
                return ((string)(this["aciLocalBackup"]));
            }
            set {
                this["aciLocalBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/GatherBooking")]
        public string aciRF {
            get {
                return ((string)(this["aciRF"]));
            }
            set {
                this["aciRF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TFI4gOfiMnABxa4UG9BuJAh4fUjayi5ySGHVB0XeT3qrgdFh8gj27ArwUUH8pBFZ")]
        public string aciDCPW {
            get {
                return ((string)(this["aciDCPW"]));
            }
            set {
                this["aciDCPW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30/12/2021")]
        public string aciTo {
            get {
                return ((string)(this["aciTo"]));
            }
            set {
                this["aciTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/11/2021")]
        public string aciFrom {
            get {
                return ((string)(this["aciFrom"]));
            }
            set {
                this["aciFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int aciWait {
            get {
                return ((int)(this["aciWait"]));
            }
            set {
                this["aciWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int aciUploadInterval {
            get {
                return ((int)(this["aciUploadInterval"]));
            }
            set {
                this["aciUploadInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Build a Bear,Reindeer Food,Cookie Decorating")]
        public string aciActivities {
            get {
                return ((string)(this["aciActivities"]));
            }
            set {
                this["aciActivities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool aciTables {
            get {
                return ((bool)(this["aciTables"]));
            }
            set {
                this["aciTables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paddington,Winnie the Pooh,Rupert,Gummy Bear")]
        public string aciTableNames {
            get {
                return ((string)(this["aciTableNames"]));
            }
            set {
                this["aciTableNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool aciUseInfo {
            get {
                return ((bool)(this["aciUseInfo"]));
            }
            set {
                this["aciUseInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/ActivityCheckIn")]
        public string aciUploadActivity {
            get {
                return ((string)(this["aciUploadActivity"]));
            }
            set {
                this["aciUploadActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true,false,true,false,true,false,true,false,true,false,true,false,true,false,true" +
            ",false,true,false")]
        public string aciChildChecked {
            get {
                return ((string)(this["aciChildChecked"]));
            }
            set {
                this["aciChildChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true,false,true,false,true,false,true,false,true,false,true,false,true,false,true" +
            ",false,true,false")]
        public string aciAdultChecked {
            get {
                return ((string)(this["aciAdultChecked"]));
            }
            set {
                this["aciAdultChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true,false,true,false,true,false,true,false,true,false,true,false,true,false,true" +
            ",false,true,false")]
        public string aciFamilyChecked {
            get {
                return ((string)(this["aciFamilyChecked"]));
            }
            set {
                this["aciFamilyChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int aciReadWait {
            get {
                return ((int)(this["aciReadWait"]));
            }
            set {
                this["aciReadWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ashcr\\Downloads\\New folder")]
        public string aciTableRead {
            get {
                return ((string)(this["aciTableRead"]));
            }
            set {
                this["aciTableRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ashcr\\Downloads\\New folder")]
        public string aciTableWrite {
            get {
                return ((string)(this["aciTableWrite"]));
            }
            set {
                this["aciTableWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int aciRemember {
            get {
                return ((int)(this["aciRemember"]));
            }
            set {
                this["aciRemember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string aciUnique {
            get {
                return ((string)(this["aciUnique"]));
            }
            set {
                this["aciUnique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool aciDeleteTables {
            get {
                return ((bool)(this["aciDeleteTables"]));
            }
            set {
                this["aciDeleteTables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ashcr\\Downloads\\New folder")]
        public string aciQuestionFile {
            get {
                return ((string)(this["aciQuestionFile"]));
            }
            set {
                this["aciQuestionFile"] = value;
            }
        }
    }
}
